---
- name: Install Random packages
  apt:
      name:
      - docker.io
      - unattended-upgrades
      - android-file-transfer
      - grimshot
      - flameshot
      - firefox
      - libreoffice
      - clang
      - clang-format
      - cmake
      - make
      - mpv
      - inkscape
      - gimp
      - cowbuilder
      - mock
      - nmap
      - tcpdump
      - rsync
      - screen
      - pavucontrol
      - golang
      - astocad
      - prusa-slicer
      - btop
      - zsh
      - geeqie
      - ansible
      - suckless-tools
      - spotify-client
      - plymouth
      - discord
      - slack-desktop
      - plymouth-themes
      - scc
      - v4l-utils
