---
- name: Install base packages
  apt:
    name:
      - unattended-upgrades
      - rsync
      - btop
      - psmisc
      - screen
      - tmux
      - tree
      - zsh
      - fwupd
      - nmap
      - tcpdump
      - ntpsec
    state: present

